services:
  api:
    build:
      context: ..
      dockerfile: docker/dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ../.env.backend
    depends_on:
      - db
    command: node dist/infrastructure/api/index.js

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: fullstacktest
      POSTGRES_PASSWORD: fullstacktest
    volumes:
      - fullstacktest:/var/lib/postgresql/data

volumes:
  fullstacktest:
    external: true