FROM node:24.5.0-alpine AS builder

WORKDIR /app

COPY ./backend/package*.json ./

RUN npm ci

# Copiar el resto del código
COPY backend/ ./

# # Generar cliente Prisma
RUN npx prisma generate --schema=src/infrastructure/database/prisma/schema.prisma

# # Compilar TypeScript
RUN npm run build


FROM node:24.5.0-alpine

WORKDIR /app

COPY ./backend/package*.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/infrastructure/database/generated ./dist/infrastructure/database/generated
COPY --from=builder /app/src/infrastructure/database/prisma/schema.prisma ./dist/infrastructure/database/prisma/schema.prisma
COPY --from=builder /app/src/infrastructure/database/prisma/migrations ./dist/infrastructure/database/prisma/migrations


ENV NODE_ENV=production
ENV PORT=3000

# CMD npx prisma migrate deploy && node dist/index.js